"""delivery_boy_and_shipment_fields

Revision ID: 7f7d6e241bcd
Revises: 
Create Date: 2026-03-07 14:27:23.838672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '7f7d6e241bcd'
down_revision = None
branch_labels = None
depends_on = None


def _run_safe(conn, fn):
    """Run fn(conn), ignore OperationalError for 'already exists' / 'duplicate'."""
    try:
        fn(conn)
    except OperationalError as e:
        msg = str(e.orig).lower() if hasattr(e, 'orig') else str(e).lower()
        if 'already exists' in msg or 'duplicate' in msg:
            pass
        else:
            raise


def upgrade():
    conn = op.get_bind()

    def create_delivery_profiles(_):
        op.create_table('delivery_profiles',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('phone', sa.String(length=32), nullable=True),
            sa.Column('vehicle_type', sa.String(length=64), nullable=True),
            sa.Column('license_number', sa.String(length=64), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.Column('created_by', sa.Integer(), nullable=True),
            sa.Column('updated_by', sa.Integer(), nullable=True),
            sa.Column('deleted_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id')
        )

    _run_safe(conn, create_delivery_profiles)

    def add_shipment_columns(_):
        with op.batch_alter_table('shipments', schema=None) as batch_op:
            batch_op.add_column(sa.Column('assigned_delivery_boy_id', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('assigned_by_logistics_id', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('assigned_time', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('pickup_time', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('delivery_time', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('delivery_attempts', sa.Integer(), nullable=False, server_default='0'))
            batch_op.add_column(sa.Column('failure_reason', sa.Text(), nullable=True))
            batch_op.create_foreign_key('fk_shipments_assigned_by', 'users', ['assigned_by_logistics_id'], ['id'])
            batch_op.create_foreign_key('fk_shipments_delivery_boy', 'delivery_profiles', ['assigned_delivery_boy_id'], ['id'])

    _run_safe(conn, add_shipment_columns)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('delivery_attempts')
        batch_op.drop_column('delivery_time')
        batch_op.drop_column('pickup_time')
        batch_op.drop_column('assigned_time')
        batch_op.drop_column('assigned_by_logistics_id')
        batch_op.drop_column('assigned_delivery_boy_id')

    op.drop_table('delivery_profiles')
    # ### end Alembic commands ###
